#!/bin/bash

# Usage :
################################################
#                                              #
# Write another script in your multicrab       #
# folder, such as :                            #
#                                              #
# ---------------------------------------------#
# #!/bin/bash                                  #
#                                              #
# export TASKS="Task1 Task2 Task3"             #
#                                              #
# ../multiStatus $*                            #
# ---------------------------------------------#
#                                              #
# Then call this script with :                 #
# ./script -U                                  #
#                                              #
################################################

rm -f report.tmp
 
echo ", ----------------- - ------ - ----- - ----- - ---- - ------- - ------- ," >> report.tmp
echo "|        Task       |  Subm  |  Run  |  Err  |  OK  |  Clear  |  Total  |" >> report.tmp
echo "- ----------------- - ------ - ----- - ----- - ---- - ------- - ------- -" >> report.tmp

ALL_SUBMITTED=0
ALL_RUNNING=0
ALL_ERROR=0
ALL_OK=0
ALL_CLEAR=0
ALL_TOTAL=0

for TASK in $TASKS
do
    # Update if option is specified
    if [[ $1 == "-U" ]]
    then
        echo "  Checking status of $TASK ... "
        crab -status -c $TASK > $TASK/status.tmp 2>&1
    fi
    
    SUBMITTED=`cat $TASK/status.tmp | grep -E "^[0-9]"                              | grep "Submitted\|Scheduled" | wc -l`
    RUNNING=`  cat $TASK/status.tmp | grep -E "^[0-9]"                              | grep "Running"   | wc -l`
    ERROR=`    cat $TASK/status.tmp | grep -E "^[0-9]" | awk '{if ($5 != 0) print}' | grep -v "Submitted\|Scheduled\|Running" | wc -l`
    OK=`       cat $TASK/status.tmp | grep -E "^[0-9]" | awk '{if ($5 == 0) print}' | grep "Done"      | wc -l`
    CLEAR=`    cat $TASK/status.tmp | grep -E "^[0-9]" | awk '{if ($5 == 0) print}' | grep "Retrieved" | wc -l`
    TOTAL=`    cat $TASK/status.tmp | grep -E "^[0-9]" | wc -l`

    echo "| $TASK | $SUBMITTED | $RUNNING | $ERROR | $OK | $CLEAR | $TOTAL |" >> report.tmp

    ALL_SUBMITTED=`echo $ALL_SUBMITTED + $SUBMITTED | bc`
    ALL_RUNNING=`echo $ALL_RUNNING + $RUNNING | bc`
    ALL_ERROR=`echo $ALL_ERROR + $ERROR | bc`
    ALL_OK=`echo $ALL_OK + $OK | bc`
    ALL_CLEAR=`echo $ALL_CLEAR + $CLEAR | bc`
    ALL_TOTAL=`echo $ALL_TOTAL + $TOTAL | bc`

done

echo "- ----------------- - ------ - ----- - ----- - ---- - ------- - ------- -" >> report.tmp

echo "| All | $ALL_SUBMITTED | $ALL_RUNNING | $ALL_ERROR | $ALL_OK | $ALL_CLEAR | $ALL_TOTAL |" >> report.tmp

ALL_SUBMITTED=`echo $ALL_SUBMITTED "*" 100 / $ALL_TOTAL | bc`
ALL_RUNNING=`echo $ALL_RUNNING "*" 100 / $ALL_TOTAL | bc`
ALL_ERROR=`echo $ALL_ERROR "*" 100 / $ALL_TOTAL | bc`
ALL_OK=`echo $ALL_OK "*" 100 / $ALL_TOTAL | bc`
ALL_CLEAR=`echo $ALL_CLEAR "*" 100 / $ALL_TOTAL | bc`
ALL_TOTAL=`echo $ALL_TOTAL "*" 100 / $ALL_TOTAL | bc`

echo "| All(percent) | ${ALL_SUBMITTED}% | ${ALL_RUNNING}% | ${ALL_ERROR}% | ${ALL_OK}% | ${ALL_CLEAR}% | ${ALL_TOTAL}% |" >> report.tmp

echo "- ----------------- - ------ - ----- - ----- - ---- - ------- - ------- -" >> report.tmp
   
cat report.tmp | column -t

rm report.tmp

