#!/bin/bash

# Usage :
################################################
#                                              #
# Write another script in your multicrab       #
# folder, such as :                            #
#                                              #
# ---------------------------------------------#
# #!/bin/bash                                  #
#                                              #
# export TASKS="Task1 Task2 Task3"             #
#                                              #
# ../multiResubmit                             #
# ---------------------------------------------#
#                                              #
# Then call this script with :                 #
# ./script -U                                  #
#                                              #
################################################


for TASK in $TASKS
do
    NRESUBMIT=`cat $TASK/status.tmp | grep -E "^[0-9]" | awk '{if ($5 != 0 || $6 != 0) print}' | grep -v "Submitted\|Scheduled\|Running" | head -n500 | wc -l`
    if [[ $NRESUBMIT -gt 0 ]]
    then
        echo Resubmitting $NRESUBMIT jobs for $TASK ...
        LIST=`cat $TASK/status.tmp | grep -E "^[0-9]" | awk '{if ($5 != 0 || $6 != 0) print}' | grep -v "Submitted\|Scheduled\|Running" | head -n500 | awk '{print $1}' | tr '\n' ',' | sed 's/,$//g'`
        crab -forceResubmit $LIST -c $TASK > log.tmp
        cat log.tmp | grep "submitted" | tail -n1
        rm log.tmp
    else
        echo No job to resubmit for $TASK
    fi 
    #crab -forceResubmit 1-500 -c $TASK
done
