#!/bin/bash

LOCAL_PWD=$PWD

CRAB_HOME=/dpm/in2p3.fr/home/cms/phedex/store/user/aaubin/
CRAB_FOLDER=May14-dileptonFix-v1
CRAB_PWD=$CRAB_HOME/$CRAB_FOLDER/

DATASETLIST="DY1jets
DY2jets
DY3jets
DY4jets
SingleT-s
SingleT-t
SingleT-tW
SingleTbar-s
SingleTbar-t
SingleTbar-tW
TBZ
TTG
TTW
TTWW
TTZ
WGToLNu2E
WGToLNu2Mu
WGToLNu2Tau
WWG
WWTo2L2Nu
WWW
WWZ
WZTo2L2Q
WZTo3LNu
WZZ
ZZTo2L2Nu
ZZTo2L2Q
ZZTo4L
ZZZ
ttbar-v1
ttbar-v2
ttbar_madgraph_1l
ttbar_madgraph_2l"

SIZETOT="0"

for DATASET in $DATASETLIST
do
	
    #SUBFOLD1=`rfdir $CRAB_PWD/$DATASET/ | grep "Beta" | awk '{print $9}'`
    #SUBFOLD2=`rfdir $CRAB_PWD/$DATASET/$SUBFOLD1 | awk '{print $9}' | head -n1`
   
    #TAG=`echo $SUBFOLD1 | sed "s|tauVetoValidationBeta_||g"`
    
    #SIZE=`rfdir $CRAB_HOME/$DATASET/$SUBFOLD1/$SUBFOLD2 | awk '{print $5}'  | tr '\n' '+' | sed 's|+$|\n|g' | bc | sed 's|^|0.000000000000954*|g' | bc | cut -c1-5`
    SIZE=`rfdir $CRAB_PWD/$DATASET | awk '{print $5}'  | tr '\n' '+' | sed 's|+$|\n|g' | bc | sed 's|^|0.000000000000954*|g' | bc | cut -c1-5`

    if [[ $SIZE != "" ]] 
    then 
        SIZETOT=`echo $SIZETOT+$SIZE | bc` 
    fi

    echo "$DATASET | $SIZE TiB"

done

echo ""
echo "Total | $SIZETOT TiB"


